# This is a basic workflow that is manually triggered

name: Package DuckDB Taco

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/checkout@v3
      with:
        repository: tableau/connector-plugin-sdk
        fetch-depth: 0
    
    - name: Create Virtual Environment
      shell: bash
      run: |
        pushd connector-packager
        python -m venv .venv
        popd
      
    - name: Package Taco
      shell: bash
      run: |
        pushd connector-packager
        source .venv/bin/activate
        python setup.py install
        python -m connector_packager.package ../../duckdb-taco/tableau_connectors/duckdb_jdbc
        popd

    - uses: actions/upload-artifact@v3
      with:
        name: duckdb_taco
        path: |
          connector-packager/packaged-connector/duckdb_jdbc.taco
